"""Public API for atomic-povray."""

from .backends import (
    Radiosity,
    RenderConfig,
    RenderResult,
    render_scene,
    scene_to_sdl,
    write_ini,
    write_scene,
)
from .config import (
    BondRule,
    CoordinationPolyhedronRule,
    CutoffPlane,
    DisplayBounds,
)
from .defaults import BondRuleSet, get_default_bonds
from .geometry import build_geometry
from .io import load_structure
from .labels import element_labels, label_atoms
from .model import (
    AtomInstance,
    AtomKey,
    Bond,
    CoordinationPolyhedron,
    GeometryModel,
    StructureModel,
)
from .primitives import (
    Color,
    CylinderPrimitive,
    Finish,
    Material,
    Primitive,
    SpherePrimitive,
    TextPrimitive,
    TriangleMeshPrimitive,
)
from .primitive_images import primitive_images
from .profile import (
    DEFAULT_PROFILE,
    AtomicPovrayProfile,
    ElementOverride,
    GeometryDefaults,
    LabelDefaults,
    RenderDefaults,
    SceneDefaults,
    StyleDefaults,
)
from .scene import (
    AreaLight,
    Background,
    Camera,
    Fog,
    PointLight,
    Scene,
    get_default_light,
    make_scene,
)
from .styling import (
    AtomSelectionRule,
    AtomStyle,
    AtomStyleOverride,
    BondStyle,
    CoordinationStyleRule,
    DepthShading,
    PolyhedronEdgeStyle,
    PolyhedronStyle,
    PolyhedronStyleOverride,
    StyleConfig,
    StyledGeometry,
    apply_styles,
    resolve_atom_styles,
)

__all__ = [
    "AreaLight",
    "AtomicPovrayProfile",
    "AtomInstance",
    "AtomKey",
    "AtomSelectionRule",
    "AtomStyle",
    "AtomStyleOverride",
    "Background",
    "Bond",
    "BondRule",
    "BondRuleSet",
    "BondStyle",
    "Camera",
    "Color",
    "CoordinationStyleRule",
    "CoordinationPolyhedron",
    "CoordinationPolyhedronRule",
    "CutoffPlane",
    "CylinderPrimitive",
    "DepthShading",
    "DEFAULT_PROFILE",
    "DisplayBounds",
    "ElementOverride",
    "Finish",
    "Fog",
    "GeometryModel",
    "GeometryDefaults",
    "LabelDefaults",
    "Material",
    "PointLight",
    "PolyhedronEdgeStyle",
    "PolyhedronStyle",
    "PolyhedronStyleOverride",
    "Primitive",
    "Radiosity",
    "RenderConfig",
    "RenderDefaults",
    "RenderResult",
    "Scene",
    "SceneDefaults",
    "SpherePrimitive",
    "StructureModel",
    "StyleConfig",
    "StyleDefaults",
    "StyledGeometry",
    "TextPrimitive",
    "TriangleMeshPrimitive",
    "apply_styles",
    "build_geometry",
    "element_labels",
    "get_default_bonds",
    "get_default_light",
    "label_atoms",
    "load_structure",
    "make_scene",
    "primitive_images",
    "render_scene",
    "resolve_atom_styles",
    "scene_to_sdl",
    "write_ini",
    "write_scene",
]


